apiVersion: v1
kind: Pod
metadata:
  name: centos
  labels:
    mycka: simplilearn
spec:
  containers:
  - name: mycontainer
    image: docker.io/centos
    command: ["/bin/ping"]
    args: ["google.com"]
