apiVersion: v1 #related to labels_selectors_pod.yml
kind: Service
metadata:
  name: myservice
spec:
  selector:
    mycka: simplilearn
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
